name: BuildTools Updater

# Controls when the action will run. 
on:
  issues:
    types: [opened]
  schedule:
    - cron: '0 12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master

      - name: 'Download BuildTools from SpigotMC'
        run: |
          rm -rf BuildTools.jar
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Configure git and Commit
        run: |
          git config --global user.email snwcreations@qq.com
          git config --global user.name SNWCreations
          git add .
          sh commit.sh
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN_FOR_SV }}
