name: Gitee Mirror Updater

# Controls when the action will run. 
on:
  issues:
    types: [opened]
  schedule:
    - cron: '30 12 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  main:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.8'
          cache: 'pip'

      - name: Install Requirements
        run: |
          pip install -U setuptools
          pip install -U wheel
          pip install -r requirements.txt
          
      - name: Working
        run: A=${{ secrets.A }} B=${{ secrets.B }} python gitee_updater.py

