# The main workflow!

name: Main workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  issues:
    types: [opened]
  schedule:
    - cron: '*/30 6,12,18 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called &#34;build&#34;
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 'Download files from SpigotMC'
        run: wget -A.json -L -N -r -np -nH -R index.html -P ./spigotversions https://hub.spigotmc.org/versions

      - name: Configure git and Commit
        run: |
          git config --global user.email snwcreations@qq.com
          git config --global user.name SNWCreations
          git add .
          git commit -m "Updated by Github Actions." -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN_FOR_SV }}